receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog/docker:
    include:
      - /var/lib/docker/containers/*/*-json.log
    start_at: end
    include_file_path: true
    include_file_name: false
    operators:
      - type: json_parser
        parse_from: body
        time_key: time
        time_format: RFC3339Nano
        message_key: log
exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true
processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    logs/gc:
      receivers: [otlp, filelog/docker]
      processors: [batch]
      exporters: [otlphttp]
